### ISSUE TITLE
Enable character type selection

### ISSUE THREAD

**Issue by christineetaylor** [christineetaylor/py-password-toy#9]
Enable users to select which of the four character types (uppercase, lowercase, numbers, symbols) are used during password generation.

**Comment by Alireza-Sampour** [comment]
I would like to work on this, could you assign this to me?

**Comment by christineetaylor** [comment]
Welcome, @Alireza-Sampour! You've been assigned to this issue.

**Comment by Alireza-Sampour** [comment]
Just for clarity: user can select one character from four character types? it is right?

**Comment by christineetaylor** [comment]
User should be able to specifically choose 1, 2 ,3 or all 4 character types to generate their password. By default, all four character types should be selected, and the user can deselect options before the password is generated.

For example, if they want a password containing only letters and numbers, they would be able to deselect `symbols` so that only characters in uppercase (`uc`), lowercase (`lc`), and `numbers` are included in the password.

**Comment by Alireza-Sampour** [comment]
I created a pull request, hope everything's fine.
